image: node:latest

deploy:
    stage: deploy
    only:
        - master
   script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set sftp:ssl-allow yes; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev dist/ ./sftpuser/viewtube/  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"