language: node_js
node_js:
  - "12"
env:
  global:
  - 'SFTP_USER=sftpuser'
install:
  - yarn
cache:
  yarn: true
after_success:
- curl --ftp-create-dirs
    -T filename
    sftp://${SFTP_USER}:${SFTP_PASSWORD}@cloud.oeger.li/sftpuser/viewtube/filename