language: node_js
node_js:
  - "12"
env:
  global:
  - 'SFTP_USER=sftpuser'
install:
  - yarn
cache:
  yarn: true
after_success:
- find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print
  -exec curl --ftp-create-dirs -T {} sftp://cloud.oeger.li/sftpuser/viewtube/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;