language: node_js
node_js:
  - "12"
install:
  - yarn
cache:
  yarn: true
after_success:
- find . -type d \( -path "./dist/.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl -k --ftp-create-dirs -T {} ftp://sl261.web.hostpoint.ch/www/viewtube.eu/ --user ${FTP_USER}:${FTP_PASSWORD} \;
