language: node_js
node_js:
  - "10"
sudo: required
install:
  - yarn
cache:
  yarn: true
script:
- yarn build
before_install:
- sudo apt-get install lftp
- sudo sysctl net.ipv6.conf.all.disable_ipv6=0
after_success:
- ls ./dist
- sudo lftp -e "mirror -R --delete --verbose=3 ./dist /www/viewtube.eu" -u ${FTP_USER},${FTP_PASSWORD} sl261.web.hostpoint.ch && exit
