language: node_js
node_js:
  - "10"
sudo: required
install:
  - yarn
cache:
  yarn: true
script:
- yarn build
before_install:
- sudo apt-get install lftp
after_success:
- ls ./dist
- sudo lftp -e "mirror -R --delete ./dist /www/viewtube.eu" -u ${FTP_USER},${FTP_PASSWORD} sl261.web.hostpoint.ch
