language: node_js
node_js:
  - "12"
env:
  global:
  - 'FTP_USER=ftpuser'
install:
  - yarn
cache:
  yarn: true
after_success:
- find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://cloud.oeger.li/ftpuser/viewtube/ --user ${FTP_USER}:${FTP_PASSWORD} \;