packageExtensions:
  "@nestjs/swagger@^5.1.0":
    peerDependencies:
      typescript: ^4.4.3
      class-transformer: "*"
      class-validator: "*"
  run-script-webpack-plugin@^0.0.11:
    peerDependencies:
      webpack: ^4.4.3
  "@typescript-eslint/experimental-utils@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  "@typescript-eslint/typescript-estree@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  eslint-plugin-jest@^24.5.0:
    peerDependencies:
      typescript: ^4.4.3
  fastify-cookie@^5.3.1:
    peerDependencies:
      fastify: ^3.22.0
  fastify-helmet@^5.3.2:
    peerDependencies:
      fastify: ^3.22.0
  fastify-multipart@^5.0.1:
    peerDependencies:
      fastify: ^3.22.0
  fork-ts-checker-webpack-plugin@^6.3.3:
    peerDependencies:
      eslint: ^7.32.0
      vue-template-compiler: ^2.6.14
  middie@*:
    dependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpIgnorePatterns:
  - ./client/**

yarnPath: .yarn/releases/yarn-3.1.1.cjs
