name: notify

on: [push]

jobs:
  send:
    
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ViewTube Deployment ${{ github.commit.ref }} successful
