name: FTP Deploy

on: 
  push:
    branches: 
      - nuxt-migration

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
     
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      
    - name: build
      run: |
        sudo cd ../viewtube-vue
        sudo yarn install
        sudo yarn build --if-present
        sudo pm2 restart viewtube-pm2.json
        
    - name: List output files
      run: ls dist
        
    - name: Notifier
      uses: GokulDas027/TelegramBridge@master
      if: always()
      with:
        chat: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        status: ${{ job.status }}
        event: ${{ github.event_name }}
        actor: ${{ github.actor }}
